# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roberto Piva
email: piva.roberto.88@gmail.com
description: Software and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.robertopiva.pro # the base hostname & protocol for your site
twitter_username: il_civitz
github_username: civitz

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
